### ISSUE TITLE
the distinct operation does not work as expected

### ISSUE THREAD

**Issue by fm94** [CN-TU/go-flows#14]
When using this [pcap](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=nb6-startup.pcap)

With the following configuration file:

```
{
    "features": [
        "packetTotalCount",
        {"distinct":["sourceIPAddress"]},
        "ipTotalLength"
    ],
    "bidirectional": false,
    "active_timeout": 0,
    "idle_timeout": 0,
    "key_features": [
        "__timeWindow1s"
    ]
}
```

The output returns (line 13 for example) 3 packets but 0 distinct sources and 0 total length. I would guess that the problem is in the distinct function[](https://github.com/CN-TU/go-flows/blob/68b64ace54e2673bbd1300654059de984dc0bf97/modules/features/operations/value.go#L426)  and specifically how it increments the count (it does not take care of all cases?).

**Comment by notti** [comment]
Beware that you said: `distinct(sourceIPAddress)` and `ipTotalLength` - there are lots of packets in there that are not IP!
Just checked the first flows and the pcap and the output looks correct:
```
1,1,431 : eth/IP/udp/dhcp
1,1,431 : eth/IP/udp/dhcp 
1,1,431 : eth/IP/udp/dhcp 
1,0,0   : eth/ppp
1,0,0   : eth/ppp
2,0,0   : eth/arp, eth/arp
1,0,0   : eth/ppp
2,1,431 : eth/IP/udp/dhcp, eth/ppp
4,1,431 : eth/IP/udp/dhcp, eth/arp, eth/arp, eth/arp
1,0,0   : eth/ppp
1,1,431 : eth/IP/udp/dhcp
3,0,0   : eth/arp, eth/arp, eth/arp
4,0,0   : eth/ppp, eth/ppp, eth/ppp
18,0,0  : tons of eth/ppp eth/ppp/ptp/ppp
```

**Comment by fm94** [comment]
True, thanks.
